version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev
    image: ease-trip-frontend:latest
    container_name: ease-trip-frontend
    depends_on:
      - ease-trip-backend
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./apps/common/src:/app/apps/common/src
      - ./apps/easy-ui/src:/app/apps/easy-ui/src
    ports:
      - '4000:4000'
    working_dir: /app
    command: 'pnpm dev:fe'

  ease-trip-backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    image: ease-trip-backend:latest
    container_name: ease-trip-backend
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./apps/common/src:/app/apps/common/src
    ports:
      - '4004:4004'
    working_dir: /app
    command: 'pnpm dev:be'
